import { Raleway } from "next/font/google";
import Header from "@/components/organisms/Header";
import Footer from "@/components/organisms/Footer";
import "@/styles/app.scss"

const raleway = Raleway({ subsets:["latin-ext"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Web Demo</title>
        <link rel="preload" href={'@/styles/fonts/RoughBattle.woff2'} as="font" type="font/woff2" crossorigin/>
        </head>
      <body className={[raleway.className]}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
